namespace TouchlineManager.Domain.Finance;

/// <summary>
/// The intent of one ledger posting, before an account turns it into an entry (master plan §6.8).
/// </summary>
/// <remarks>
/// <para>
/// A posting is what a workflow asks for; a <see cref="LedgerEntry"/> is what an account records once it has
/// checked the move against its own balances. Keeping them apart is what makes <see cref="ClubAccount.Post"/>
/// the only place a balance changes and the only place the rules are applied — a caller proposes a delta and
/// a reason, and the account decides whether the club can afford it (`FIN-10`, `FIN-13`).
/// </para>
/// <para>
/// Both a cash delta and a reserved delta are carried, because the two move independently: a wage is a debit
/// to cash, a leading bid is a commitment of reserved funds, and outbidding somebody releases their
/// reservation without touching cash (`FIN-7`, `FIN-10`, `TRF-7`).
/// </para>
/// </remarks>
/// <param name="EntryId">The identity the resulting entry will carry, generated by the server (`ID-1`).</param>
/// <param name="Category">What the move is.</param>
/// <param name="CashDeltaMinor">The signed change to cash, in minor units.</param>
/// <param name="ReservedDeltaMinor">The signed change to reserved funds, in minor units.</param>
/// <param name="SourceType">The kind of workflow that produced it.</param>
/// <param name="SourceId">The thing that produced it, or null.</param>
/// <param name="CorrelationId">
/// The key the whole operation shares. Unique per category, it is what an ordinary retry collides with
/// rather than posting twice (`FIN-17`).
/// </param>
/// <param name="DescriptionTemplate">The stable template key that describes the entry.</param>
/// <param name="DescriptionParametersJson">The template's parameters, as a stored document.</param>
/// <param name="ReversesEntryId">
/// The entry this one corrects, when the posting is an operator's compensating entry (`FIN-12`), or null.
/// </param>
public sealed record LedgerPosting(
    Guid EntryId,
    LedgerCategory Category,
    long CashDeltaMinor,
    long ReservedDeltaMinor,
    LedgerSourceType SourceType,
    Guid? SourceId,
    string CorrelationId,
    string DescriptionTemplate,
    string DescriptionParametersJson,
    Guid? ReversesEntryId = null);
