<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>FootballManager.Worker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FootballManager.Application\FootballManager.Application.csproj" />
    <ProjectReference Include="..\..\src\FootballManager.Infrastructure\FootballManager.Infrastructure.csproj" />
  </ItemGroup>

</Project>
