// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TouchlineManager.Infrastructure.Persistence;

#nullable disable

namespace TouchlineManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TouchlineManagerDbContext))]
    [Migration("20260924105510_WorldPyramidAndOnboarding")]
    partial class WorldPyramidAndOnboarding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TouchlineManager.Domain.Auth.EmailToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_email_tokens_token_hash");

                    b.HasIndex("UserId", "Purpose")
                        .HasDatabaseName("ix_email_tokens_user_id_purpose");

                    b.ToTable("email_tokens", "auth", t =>
                        {
                            t.HasCheckConstraint("ck_email_tokens_expiry", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.Auth.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("IpPrefixHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_prefix_hash");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_agent_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_sessions_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_sessions_token_hash");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_refresh_sessions_user_id_revoked_at");

                    b.ToTable("refresh_sessions", "auth", t =>
                        {
                            t.HasCheckConstraint("ck_refresh_sessions_expiry", "expires_at > issued_at");

                            t.HasCheckConstraint("ck_refresh_sessions_revocation", "(revoked_at is null and revocation_reason is null) or (revoked_at is not null and revocation_reason is not null)");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockoutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_until");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("normalized_display_name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedDisplayName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_display_name");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.ToTable("users", "auth", t =>
                        {
                            t.HasCheckConstraint("ck_users_failed_login_count", "failed_login_count >= 0");

                            t.HasCheckConstraint("ck_users_status", "status in ('pending', 'active', 'suspended', 'deletion_pending', 'anonymized')");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.Auth.UserConsent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_type");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DocumentType")
                        .HasDatabaseName("ix_user_consents_user_id_document_type");

                    b.ToTable("user_consents", "auth", t =>
                        {
                            t.HasCheckConstraint("ck_user_consents_document_type", "document_type in ('terms', 'privacy')");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.Auth.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Role")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.HasKey("UserId", "Role");

                    b.ToTable("user_roles", "auth");
                });

            modelBuilder.Entity("TouchlineManager.Domain.Competition.ClubSeasonEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ClosingCashMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("closing_cash_minor");

                    b.Property<int?>("ClosingReputation")
                        .HasColumnType("integer")
                        .HasColumnName("closing_reputation");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DivisionSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("division_season_id");

                    b.Property<int?>("FinalRank")
                        .HasColumnType("integer")
                        .HasColumnName("final_rank");

                    b.Property<string>("InitialControlType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("initial_control_type");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_promoted");

                    b.Property<bool>("IsRelegated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_relegated");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ClubId")
                        .HasDatabaseName("ix_club_season_entries_club_id");

                    b.HasIndex("DivisionSeasonId", "ClubId")
                        .IsUnique()
                        .HasDatabaseName("ux_club_season_entries_division_season_id_club_id");

                    b.HasIndex("SeasonId", "ClubId")
                        .IsUnique()
                        .HasDatabaseName("ux_club_season_entries_season_id_club_id");

                    b.ToTable("club_season_entries", "competition", t =>
                        {
                            t.HasCheckConstraint("ck_club_season_entries_closing_cash", "closing_cash_minor is null or closing_cash_minor >= 0");

                            t.HasCheckConstraint("ck_club_season_entries_control_type", "initial_control_type in ('ai', 'human')");

                            t.HasCheckConstraint("ck_club_season_entries_final_rank", "final_rank is null or final_rank >= 1");

                            t.HasCheckConstraint("ck_club_season_entries_movement", "not (is_promoted and is_relegated)");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.Competition.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_season_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("TierNumber")
                        .HasColumnType("integer")
                        .HasColumnName("tier_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedSeasonId");

                    b.HasIndex("CountryId", "TierNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_divisions_country_id_tier_number");

                    b.ToTable("divisions", "competition", t =>
                        {
                            t.HasCheckConstraint("ck_divisions_capacity", "capacity = 18");

                            t.HasCheckConstraint("ck_divisions_status", "status in ('provisioning', 'active', 'retired')");

                            t.HasCheckConstraint("ck_divisions_tier_number", "tier_number >= 1");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.Competition.DivisionSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("division_id");

                    b.Property<string>("ScheduleSeed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("schedule_seed");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTimeOffset?>("StandingsFinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("standings_finalized_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TieDrawHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tie_draw_hash");

                    b.Property<string>("TieDrawSeed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tie_draw_seed");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_division_seasons_season_id");

                    b.HasIndex("DivisionId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("ux_division_seasons_division_id_season_id");

                    b.ToTable("division_seasons", "competition", t =>
                        {
                            t.HasCheckConstraint("ck_division_seasons_status", "status in ('scheduled', 'active', 'completed')");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.Competition.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("display_label");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<int>("GameYear")
                        .HasColumnType("integer")
                        .HasColumnName("game_year");

                    b.Property<DateTimeOffset>("RolloverEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rollover_ends_at");

                    b.Property<string>("RuleSetVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rule_set_version");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_seasons_world_id_sequence_number");

                    b.ToTable("seasons", "competition", t =>
                        {
                            t.HasCheckConstraint("ck_seasons_sequence_number", "sequence_number >= 1");

                            t.HasCheckConstraint("ck_seasons_status", "status in ('scheduled', 'active', 'rollover', 'completed')");

                            t.HasCheckConstraint("ck_seasons_window", "ends_at >= starts_at and rollover_ends_at >= ends_at");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.Finance.ClubAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CashMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("cash_minor");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("LastLedgerSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_ledger_sequence");

                    b.Property<long>("ReservedMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved_minor");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ClubId")
                        .IsUnique()
                        .HasDatabaseName("ux_club_accounts_club_id");

                    b.ToTable("club_accounts", "finance", t =>
                        {
                            t.HasCheckConstraint("ck_club_accounts_cash_nonnegative", "cash_minor >= 0");

                            t.HasCheckConstraint("ck_club_accounts_ledger_sequence", "last_ledger_sequence >= 0");

                            t.HasCheckConstraint("ck_club_accounts_reserved_nonnegative", "reserved_minor >= 0");

                            t.HasCheckConstraint("ck_club_accounts_reserved_within_cash", "reserved_minor <= cash_minor");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.World.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BadgeSeed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("badge_seed");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("city");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FoundingGameYear")
                        .HasColumnType("integer")
                        .HasColumnName("founding_game_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("region");

                    b.Property<int>("Reputation")
                        .HasColumnType("integer")
                        .HasColumnName("reputation");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("short_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<long>("StadiumBaseline")
                        .HasColumnType("bigint")
                        .HasColumnName("stadium_baseline");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_clubs_country_id");

                    b.HasIndex("WorldId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_clubs_world_id_normalized_name");

                    b.HasIndex("WorldId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_clubs_world_id_slug");

                    b.ToTable("clubs", "world", t =>
                        {
                            t.HasCheckConstraint("ck_clubs_reputation", "reputation between 1 and 100");

                            t.HasCheckConstraint("ck_clubs_stadium_baseline", "stadium_baseline >= 0");

                            t.HasCheckConstraint("ck_clubs_status", "status in ('active', 'retired')");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.World.ClubTenure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<string>("ControlStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("control_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EndReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("TakeoverIdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("takeover_idempotency_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ClubId")
                        .IsUnique()
                        .HasDatabaseName("ux_club_tenures_open_club")
                        .HasFilter("control_status <> 'closed'");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasDatabaseName("ux_club_tenures_open_manager")
                        .HasFilter("control_status <> 'closed'");

                    b.HasIndex("TakeoverIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_club_tenures_takeover_idempotency_key");

                    b.HasIndex("ManagerId", "ControlStatus")
                        .HasDatabaseName("ix_club_tenures_manager_id_control_status");

                    b.ToTable("club_tenures", "world", t =>
                        {
                            t.HasCheckConstraint("ck_club_tenures_control_status", "control_status in ('active', 'inactive', 'closed')");

                            t.HasCheckConstraint("ck_club_tenures_end_reason", "(ended_at is null and end_reason is null) or (ended_at is not null and end_reason is not null)");

                            t.HasCheckConstraint("ck_club_tenures_end_reason_value", "end_reason is null or end_reason in ('resigned', 'inactivity_closed', 'administrator_closed')");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.World.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("NamePoolKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name_pool_key");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_countries_world_id_code");

                    b.ToTable("countries", "world", t =>
                        {
                            t.HasCheckConstraint("ck_countries_code", "char_length(code) = 3 and code = upper(code)");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.World.DivisionProvisioningRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureDiagnostics")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_diagnostics");

                    b.Property<string>("GenerationSeed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("generation_seed");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_season_id");

                    b.Property<int>("TargetTier")
                        .HasColumnType("integer")
                        .HasColumnName("target_tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "TargetTier")
                        .IsUnique()
                        .HasDatabaseName("ux_division_provisioning_requests_country_id_target_tier");

                    b.ToTable("division_provisioning_requests", "world", t =>
                        {
                            t.HasCheckConstraint("ck_division_provisioning_requests_status", "status in ('requested', 'running', 'completed', 'failed')");

                            t.HasCheckConstraint("ck_division_provisioning_requests_target_tier", "target_tier >= 2");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.World.GameWorld", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentSeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("current_season_number");

                    b.Property<TimeOnly>("KickoffUtc")
                        .HasColumnType("time without time zone")
                        .HasColumnName("kickoff_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("RuleSetVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rule_set_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_game_worlds_name");

                    b.ToTable("game_worlds", "world", t =>
                        {
                            t.HasCheckConstraint("ck_game_worlds_season_number", "current_season_number >= 1");

                            t.HasCheckConstraint("ck_game_worlds_status", "status in ('active', 'frozen', 'retired')");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.World.GenerationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccountsCreated")
                        .HasColumnType("integer")
                        .HasColumnName("accounts_created");

                    b.Property<int>("ClubsCreated")
                        .HasColumnType("integer")
                        .HasColumnName("clubs_created");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CountriesCreated")
                        .HasColumnType("integer")
                        .HasColumnName("countries_created");

                    b.Property<string>("Diagnostics")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("diagnostics");

                    b.Property<string>("GeneratorVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("generator_version");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("input_hash");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<int>("PlayersCreated")
                        .HasColumnType("integer")
                        .HasColumnName("players_created");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("seed");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "StartedAt")
                        .HasDatabaseName("ix_generation_runs_kind_started_at");

                    b.ToTable("generation_runs", "world", t =>
                        {
                            t.HasCheckConstraint("ck_generation_runs_counts", "countries_created >= 0 and clubs_created >= 0 and players_created >= 0 and accounts_created >= 0");

                            t.HasCheckConstraint("ck_generation_runs_kind", "kind in ('world_bootstrap', 'division_provisioning')");

                            t.HasCheckConstraint("ck_generation_runs_status", "status in ('running', 'succeeded', 'failed')");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.World.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<int>("Reputation")
                        .HasColumnType("integer")
                        .HasColumnName("reputation");

                    b.Property<DateTimeOffset?>("TakeoverCooldownUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("takeover_cooldown_until");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_managers_user_id");

                    b.ToTable("managers", "world");
                });

            modelBuilder.Entity("TouchlineManager.Infrastructure.Persistence.Entities.OpsAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_metadata");

                    b.Property<string>("BeforeMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_metadata");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_hash");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_log_correlation_id");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_log_actor_user_id_occurred_at");

                    b.HasIndex("TargetType", "TargetId", "OccurredAt")
                        .HasDatabaseName("ix_audit_log_target_occurred_at");

                    b.ToTable("audit_log", "ops", t =>
                        {
                            t.HasCheckConstraint("ck_audit_log_actor_type", "actor_type in ('user', 'service', 'anonymous')");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Infrastructure.Persistence.Entities.OpsJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business_key");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("job_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("LeaseUntil")
                        .HasDatabaseName("ix_jobs_lease_until")
                        .HasFilter("status = 'leased'");

                    b.HasIndex("JobType", "BusinessKey")
                        .IsUnique()
                        .HasDatabaseName("ux_jobs_job_type_business_key");

                    b.HasIndex("Status", "DueAt", "Priority")
                        .HasDatabaseName("ix_jobs_status_due_at_priority");

                    b.ToTable("jobs", "ops", t =>
                        {
                            t.HasCheckConstraint("ck_jobs_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_jobs_lease_consistency", "(status = 'leased' and lease_owner is not null and lease_until is not null) or (status <> 'leased' and lease_owner is null and lease_until is null)");

                            t.HasCheckConstraint("ck_jobs_max_attempts", "max_attempts >= 1");

                            t.HasCheckConstraint("ck_jobs_priority", "priority >= 0");

                            t.HasCheckConstraint("ck_jobs_status", "status in ('pending', 'leased', 'completed', 'dead_letter')");
                        });
                });

            modelBuilder.Entity("TouchlineManager.Domain.Auth.EmailToken", b =>
                {
                    b.HasOne("TouchlineManager.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.Auth.RefreshSession", b =>
                {
                    b.HasOne("TouchlineManager.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.Auth.UserConsent", b =>
                {
                    b.HasOne("TouchlineManager.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.Auth.UserRoleAssignment", b =>
                {
                    b.HasOne("TouchlineManager.Domain.Auth.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.Competition.ClubSeasonEntry", b =>
                {
                    b.HasOne("TouchlineManager.Domain.World.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TouchlineManager.Domain.Competition.DivisionSeason", null)
                        .WithMany()
                        .HasForeignKey("DivisionSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TouchlineManager.Domain.Competition.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.Competition.Division", b =>
                {
                    b.HasOne("TouchlineManager.Domain.World.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TouchlineManager.Domain.Competition.Season", null)
                        .WithMany()
                        .HasForeignKey("CreatedSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.Competition.DivisionSeason", b =>
                {
                    b.HasOne("TouchlineManager.Domain.Competition.Division", null)
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TouchlineManager.Domain.Competition.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.Competition.Season", b =>
                {
                    b.HasOne("TouchlineManager.Domain.World.GameWorld", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.Finance.ClubAccount", b =>
                {
                    b.HasOne("TouchlineManager.Domain.World.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.World.Club", b =>
                {
                    b.HasOne("TouchlineManager.Domain.World.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TouchlineManager.Domain.World.GameWorld", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.World.ClubTenure", b =>
                {
                    b.HasOne("TouchlineManager.Domain.World.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TouchlineManager.Domain.World.Manager", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.World.Country", b =>
                {
                    b.HasOne("TouchlineManager.Domain.World.GameWorld", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.World.DivisionProvisioningRequest", b =>
                {
                    b.HasOne("TouchlineManager.Domain.World.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.World.Manager", b =>
                {
                    b.HasOne("TouchlineManager.Domain.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TouchlineManager.Domain.Auth.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
