// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TouchlineManager.Infrastructure.Persistence;

#nullable disable

namespace TouchlineManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TouchlineManagerDbContext))]
    [Migration("20260923222256_InitialOpsJobs")]
    partial class InitialOpsJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TouchlineManager.Infrastructure.Persistence.Entities.OpsJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business_key");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("job_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("LeaseUntil")
                        .HasDatabaseName("ix_jobs_lease_until")
                        .HasFilter("status = 'leased'");

                    b.HasIndex("JobType", "BusinessKey")
                        .IsUnique()
                        .HasDatabaseName("ux_jobs_job_type_business_key");

                    b.HasIndex("Status", "DueAt", "Priority")
                        .HasDatabaseName("ix_jobs_status_due_at_priority");

                    b.ToTable("jobs", "ops", t =>
                        {
                            t.HasCheckConstraint("ck_jobs_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_jobs_lease_consistency", "(status = 'leased' and lease_owner is not null and lease_until is not null) or (status <> 'leased' and lease_owner is null and lease_until is null)");

                            t.HasCheckConstraint("ck_jobs_max_attempts", "max_attempts >= 1");

                            t.HasCheckConstraint("ck_jobs_priority", "priority >= 0");

                            t.HasCheckConstraint("ck_jobs_status", "status in ('pending', 'leased', 'completed', 'dead_letter')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
