<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TouchlineManager.Domain\TouchlineManager.Domain.csproj" />
    <ProjectReference Include="..\TouchlineManager.Contracts\TouchlineManager.Contracts.csproj" />
    <ProjectReference Include="..\TouchlineManager.MatchEngine\TouchlineManager.MatchEngine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
